@extends('layouts.default')
@section('content')
<div class=" white_transparent_bg rounded">
	<h2 class="p-3 text-center">References</h2>
	<p class="p-5">
	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla urna porttitor rhoncus dolor. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Interdum posuere lorem ipsum dolor. Duis convallis convallis tellus id interdum velit laoreet. Cras ornare arcu dui vivamus arcu felis. Vitae congue mauris rhoncus aenean vel. Neque vitae tempus quam pellentesque. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Molestie ac feugiat sed lectus vestibulum. Eu augue ut lectus arcu. Sit amet facilisis magna etiam tempor orci. At quis risus sed vulputate odio ut enim blandit. Interdum consectetur libero id faucibus nisl tincidunt eget. Duis convallis convallis tellus id interdum. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Ultrices dui sapien eget mi proin sed libero. Nisi lacus sed viverra tellus in hac habitasse.

Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Ante in nibh mauris cursus mattis molestie. Diam in arcu cursus euismod. Tellus orci ac auctor augue mauris augue neque gravida in. Odio ut enim blandit volutpat maecenas volutpat blandit. Consectetur adipiscing elit ut aliquam purus sit. Ac ut consequat semper viverra nam libero. Ipsum consequat nisl vel pretium lectus quam id leo. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Blandit massa enim nec dui nunc mattis. Porta non pulvinar neque laoreet suspendisse interdum. Viverra justo nec ultrices dui. Commodo sed egestas egestas fringilla phasellus. Tellus integer feugiat scelerisque varius. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Convallis tellus id interdum velit. Non pulvinar neque laoreet suspendisse. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Massa sed elementum tempus egestas sed sed.

Id velit ut tortor pretium viverra suspendisse potenti nullam. Cras sed felis eget velit aliquet sagittis id. Risus in hendrerit gravida rutrum. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sagittis nisl rhoncus mattis rhoncus urna neque. Tincidunt vitae semper quis lectus. Mattis vulputate enim nulla aliquet porttitor lacus. Elementum integer enim neque volutpat. Fames ac turpis egestas sed tempus urna et pharetra. Rhoncus urna neque viverra justo nec ultrices dui sapien. Mauris nunc congue nisi vitae suscipit tellus mauris a. Fringilla urna porttitor rhoncus dolor purus non. Orci ac auctor augue mauris augue neque gravida in. Fringilla urna porttitor rhoncus dolor purus. Aliquam ultrices sagittis orci a. Lacus laoreet non curabitur gravida arcu ac tortor dignissim.

Condimentum mattis pellentesque id nibh tortor. Vulputate odio ut enim blandit volutpat maecenas volutpat. In arcu cursus euismod quis viverra nibh. Et malesuada fames ac turpis egestas sed tempus urna. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Fusce id velit ut tortor pretium viverra suspendisse potenti. Massa id neque aliquam vestibulum morbi. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Eu mi bibendum neque egestas congue. Diam vel quam elementum pulvinar etiam. Elementum eu facilisis sed odio. Accumsan tortor posuere ac ut consequat. Lacus vel facilisis volutpat est. In dictum non consectetur a erat. Nulla facilisi nullam vehicula ipsum a arcu. At varius vel pharetra vel turpis nunc eget. Est ultricies integer quis auctor elit sed vulputate mi sit. Sed vulputate odio ut enim blandit volutpat maecenas.
</p>
</div>
@endsection